[package]
name = "eth-schnorrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = {version = "*", features = [ "rand-std" , "hashes-std"]}
keccak-hash = "0.10.0"   